name: GlobalUUIDCache
main: dank.memes.uuidcache.GlobalUUIDCachePlugin
version: ${project.version}
author: vemacs
description: Re-adds global UUID cache into modern Spigot. Original source from SpigotMC.
